In [1]:
import numpy as np
from instances import (
    generate_copying_instance,
    generate_selective_copying_instance,
    generate_in_context_recall_instance,
    generate_noisy_in_context_recall_instance,
    generate_vocab_permutations,
    generate_fuzzy_in_context_recall_instance,
    generate_kv_map,
    generate_memorization_instance
)

In [ ]:
# target ignore token = -100

In [ ]:
inputs, targets = generate_copying_instance(vocab_size=8, seq_len=20, num_tokens_to_copy=5)
inputs, targets
# copy token = 7
# blank token = 6

(array([1, 3, 0, 5, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 6, 6, 6, 6, 6]),
 array([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100,    1,    3,    0,    5,    3]))

In [ ]:
inputs, targets = generate_selective_copying_instance(vocab_size=8, seq_len=20, num_tokens_to_copy=5)
inputs, targets
# copy token = 7
# blank token = 6

(array([6, 6, 6, 5, 6, 6, 0, 2, 6, 6, 6, 6, 0, 3, 7, 6, 6, 6, 6, 6]),
 array([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100,    5,    0,    2,    0,    3]))

In [ ]:
inputs, shifted_inputs = generate_in_context_recall_instance(vocab_size=12, seq_len=20, is_training=True, noise_vocab_size=0)
inputs, shifted_inputs
# copy token = 11
# key vocab [0, 1, 2, 3, 4]
# value vocab [5, 6, 7, 8, 9]

(array([ 0,  5,  1,  9,  1,  9,  2,  8,  0,  5,  2,  8,  0,  5,  3,  5,  3,
         5, 11,  0]),
 array([ 5,  1,  9,  1,  9,  2,  8,  0,  5,  2,  8,  0,  5,  3,  5,  3,  5,
        11,  0,  5]))

In [ ]:
inputs, targets = generate_in_context_recall_instance(vocab_size=12, seq_len=20, is_training=False, noise_vocab_size=0)
inputs, targets
# copy token = 11
# key vocab [0, 1, 2, 3, 4]
# value vocab [5, 6, 7, 8, 9]

(array([ 3,  7,  4, 10,  0, 10,  0, 10,  3,  7,  2,  9,  3,  7,  2,  9,  1,
        10, 11,  0]),
 array([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100,   10]))

In [3]:
inputs, shifted_inputs = generate_noisy_in_context_recall_instance(vocab_size=16, seq_len=20, is_training=True, noise_vocab_size=3)
inputs, shifted_inputs
# copy token = 15
# key vocab [0, 1, 2, 3, 4]
# value vocab [5, 6, 7, 8, 9]
# noise vocab [12, 13, 14]

(array([ 2,  7, 13, 12,  0,  8, 12, 14,  1,  9,  1,  9,  0,  8, 13, 14,  3,
        10, 15,  3]),
 array([ 7, 13, 12,  0,  8, 12, 14,  1,  9,  1,  9,  0,  8, 13, 14,  3, 10,
        15,  3, 10]))

In [4]:
inputs, targets = generate_noisy_in_context_recall_instance(vocab_size=16, seq_len=20, is_training=False, noise_vocab_size=3)
inputs, targets
# copy token = 15
# key vocab [0, 1, 2, 3, 4]
# value vocab [5, 6, 7, 8, 9]
# noise vocab [12, 13, 14]

(array([ 2,  8,  3, 11,  3, 11,  0,  8,  0,  8,  5, 11,  5, 11,  3, 11,  0,
         8, 15,  0]),
 array([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100,    8]))

In [4]:
vocab = np.arange(8)
generate_vocab_permutations(vocab, token_motif_size=1)

[(np.int64(0),),
 (np.int64(1),),
 (np.int64(2),),
 (np.int64(3),),
 (np.int64(4),),
 (np.int64(5),),
 (np.int64(6),),
 (np.int64(7),)]

In [8]:
vocab = np.arange(4)
generate_vocab_permutations(vocab, token_motif_size=2)

[(np.int64(0), np.int64(1)),
 (np.int64(0), np.int64(2)),
 (np.int64(0), np.int64(3)),
 (np.int64(1), np.int64(0)),
 (np.int64(1), np.int64(2)),
 (np.int64(1), np.int64(3)),
 (np.int64(2), np.int64(0)),
 (np.int64(2), np.int64(1)),
 (np.int64(2), np.int64(3)),
 (np.int64(3), np.int64(0)),
 (np.int64(3), np.int64(1)),
 (np.int64(3), np.int64(2))]

In [2]:
inputs, shifted_inputs = generate_fuzzy_in_context_recall_instance(vocab_size=12, seq_len=20, k_motif_size=3, v_motif_size=3, is_training=True, noise_vocab_size=0)
inputs, shifted_inputs
# copy token = 11
# pad token = 10
# key vocab [0, 1, 2, 3, 4]
# value vocab [5, 6, 7, 8, 9]

(array([10, 10,  0,  3,  8,  6,  9,  0,  9,  7,  0,  2,  9,  8,  5, 11,  0,
         3,  8,  6]),
 array([10,  0,  3,  8,  6,  9,  0,  9,  7,  0,  2,  9,  8,  5, 11,  0,  3,
         8,  6,  9]))

In [3]:
inputs, targets = generate_fuzzy_in_context_recall_instance(vocab_size=12, seq_len=20, k_motif_size=3, v_motif_size=3, is_training=False, noise_vocab_size=0)
inputs, targets
# copy token = 11
# pad token = 10
# key vocab [0, 1, 2, 3, 4]
# value vocab [5, 6, 7, 8, 9]

(array([10, 10, 10, 10, 10,  2,  4,  1,  9,  8,  3,  0,  2,  9,  6, 11,  3,
         0,  2,  9]),
 array([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100,    9,    6]))

In [ ]:
generate_kv_map(vocab_size=8, k_motif_size=1, v_motif_size=1)
# key vocab [0, 1, 2, 3]
# value vocab [4, 5, 6, 7]

{(np.int64(2),): (np.int64(6),),
 (np.int64(0),): (np.int64(4),),
 (np.int64(3),): (np.int64(7),),
 (np.int64(1),): (np.int64(5),)}

In [2]:
inputs, targets = generate_memorization_instance(vocab_size=8, seq_len=20)
inputs, targets
# insert token = 7

(array([1, 7, 1, 7, 2, 7, 1, 7, 0, 7, 1, 7, 0, 7, 1, 7, 0, 7, 2, 7]),
 array([-100,    4, -100,    4, -100,    6, -100,    4, -100,    3, -100,
           4, -100,    3, -100,    4, -100,    3, -100,    6]))